#ifndef KSQLCONNECTOR_GLOBAL_H
#define KSQLCONNECTOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KSQLCONNECTOR_LIBRARY)
#  define KSQLCONNECTORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define KSQLCONNECTORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // KSQLCONNECTOR_GLOBAL_H
